version: '3.8'
services:
  video-summary:
    build: .
    container_name: video-summary
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped 